# 终端下关闭连体字
font_family      family="Maple Mono Normal NF CN" features="-calt"
# font_family      FiraCode Nerd Font
font_size        10.0

# https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
# kitty作者建议不使用NF字体
# Nerd Fonts v3.3.0
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono

# https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy
# 这会让浅色背景上的深色文字看起来更厚，浅色背景上的浅色文字显得更薄
text_composition_strategy 1.7 10

# 历史记录
scrollback_lines 5000
# in MB: maybe 10000 line per MB, max is 4GB.
scrollback_pager_history_size 100
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

# Browse scrollback buffer in pager
# default key h, used to switch window.
map kitty_mod+/ show_scrollback

# 关闭audio提示音
enable_audio_bell no

# 光标厚度，默认1.5
cursor_beam_thickness 2
# 光标闪烁停止时间（包括文字）
cursor_stop_blinking_after 15.0

# 光标动画
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 20

# 字体行高
modify_font cell_height 130%

#single_window_margin_width 0

# 分割线宽度
window_border_width     0.5pt
# 减少分割线绘制
draw_minimal_borders yes
# 分割线之间的间距，此config会覆盖上述配置
# window_margin_width   3

# 字符与窗口分隔之间的间距 （top,horizontal,bottom)
window_padding_width 2 5 2

# 不生效
# hide_window_decorations titlebar-and-corners
# 隐藏titil bar
hide_window_decorations no

enabled_layouts Tall, *

tab_bar_edge top
tab_bar_margin_height 3.0 2.0
tab_bar_margin_width 3.0
tab_bar_align left
tab_bar_style       powerline
tab_bar_show_new_tab_button yes
tab_powerline_style round 
tab_title_template "📁{fmt.fg.tab}TAB({index})"
# 有点卡
# tab_title_template "{index}.{tab.active_oldest_wd[tab.active_oldest_wd.rfind('/')+1:]}"

# Performance
repaint_delay 6
input_delay 1
sync_to_monitor no

# Scroller bar (v0.43+)
scrollbar_width 1
scrollbar_hover_width 1.5
scrollbar_radius 0.5

## Custom KeyBindings
# quit kitty
map cmd+q quit
# quit current tab
map cmd+w close_tab

map f1 new_window
map f2 new_tab
map kitty_mod+enter new_window_with_cwd
map kitty_mod+t new_tab_with_cwd

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9


# here use kitty_mod ,not ctrl used in nvim.
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window top
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
# previous focus window
map kitty_mod+p nth_window -1

# swap current active window with the previous window
map kitty_mod+left move_window_backward
# swap curent active window with the next window
map kitty_mod+right move_window_forward
# move current active window to the top first window
map kitty_mod+up move_window_to_top

# moves the window into a new OS window
map kitty_mod+f1 detach_window

# close all other windows in current tab
map kitty_mod+f9 close_other_windows_in_tab

map kitty_mod+x toggle_layout stack

# add -i to ingore case
map kitty_mod+f launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay less +G -R -i

# 使用patched原因是 原版主题 zsh auto-suggestion 看不清（https://github.com/blinksh/blink/issues/381）
# include solarized/Solarized Dark - Patched.conf
include catppuccin/latte.conf


# 选中状态颜色改为反色（https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.selection_foreground）
# 必须在 color scheme 下面，部分主题中有设置颜色，但是不好用，看不清
selection_foreground  none
selection_background  none
