# Zed One Light - Kitty Theme
foreground            #2a2c33
background            #fafafa
selection_foreground  none
selection_background  #dfdfe0
cursor                #5c78e2
cursor_text_color     #fafafa

# URL 下划线颜色
url_color             #5c78e2

# 16 终端色盘
# Black
color0                #000000
color8                #555555
# Red
color1                #de3e35
color9                #de3e35
# Green
color2                #3f953a
color10               #3f953a
# Yellow
color3                #d2b67c
color11               #d2b67c
# Blue
color4                #2f5af3
color12               #2f5af3
# Magenta
color5                #950095
color13               #a00095
# Cyan
color6                #0997b3
color14               #0bbcd6
# White
color7                #bbbbbb
color15               #ffffff