# Zed One Dark - Kitty Theme
foreground            #abb2bf
background            #282c34
selection_foreground  none
selection_background  #363c46
cursor                #74ade8
cursor_text_color     #282c34

# URL 下划线颜色
url_color             #74ade8

# 16 终端色盘
# Black
color0                #282c34
color8                #636d83
# Red
color1                #e06c75
color9                #ea858b
# Green
color2                #98c379
color10               #aad581
# Yellow
color3                #e5c07b
color11               #ffd885
# Blue
color4                #61afef
color12               #85c1ff
# Magenta
color5                #c678dd
color13               #d398eb
# Cyan
color6                #56b6c2
color14               #6ed5de
# White
color7                #abb2bf
color15               #fafafa
